### ISSUE TITLE
Error after creating a publishfrom transaction 

### ISSUE THREAD

**Issue by bitcartel** [MultiChain/multichain-explorer#15]
```
Traceback (most recent call last):
  File "Mce/DataStore.py", line 2851, in catch_up
    if not store.catch_up_rpc(dircfg):
  File "Mce/DataStore.py", line 3083, in catch_up_rpc
    store.import_block(block, chain = chain)
  File "Mce/DataStore.py", line 1193, in import_block
    tx['tx_id'] = store.import_and_commit_tx(tx, pos == 0, chain)
  File "Mce/DataStore.py", line 2175, in import_and_commit_tx
    tx_id = store.import_tx(tx, is_coinbase, chain)
  File "Mce/DataStore.py", line 2115, in import_tx
    address = util.hash_to_address_multichain(vers, pubkey_hash, checksum)
  File "Mce/util.py", line 142, in hash_to_address_multichain
    vh += hash[pos:pos+5]
TypeError: unhashable type
```

**Comment by bitcartel** [comment]
Fixed https://github.com/MultiChain/multichain-explorer/commit/a2fb20b047a76384b8b220ffd9dc44810dc8a08c
