### ISSUE TITLE
It will always be "connection refused"  and multichaind will always to abort 

### ISSUE THREAD

**Issue by xbee** [MultiChain/multichain-explorer#28]
error:
```
127.0.0.1 - - [07/Nov/2017 20:52:34] "GET /logo32.png HTTP/1.1" 200 1376
RPC failed: [Errno socket error] [Errno 61] Connection refused
catch_up_rpc: abort
Opened /Users/michael/.multichain/monet/blocks/blk00000.dat
Exception: [Errno socket error] [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 321, in __call__
    handler(page)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1194, in handle_tx
    return abe.show_tx(page, tx)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1668, in show_tx
    row_to_html(txout, 'o', 'i', 'Not yet redeemed')
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1595, in row_to_html
    abe.show_tx_row_to_html_impl(chain, body, asset_txid_dict, binscript, script_type, data)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1261, in show_tx_row_to_html_impl
    assetref = asset_txid_dict[dict['assetref']]['assetref']
KeyError: 'b21f78291b609eceffa576717ebb1110'
127.0.0.1 - - [07/Nov/2017 20:52:40] "GET /MultiChain%20chain1/tx/e4cbcb37c42cd8c65ade711b165f431a49dd9351854b29e8d36c830a7bddc6a0 HTTP/1.1" 500 59
RPC failed: [Errno socket error] [Errno 61] Connection refused
catch_up_rpc: abort
Opened /Users/michael/.multichain/monet/blocks/blk00000.dat
Exception: [Errno socket error] [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 321, in __call__
    handler(page)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1194, in handle_tx
    return abe.show_tx(page, tx)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1668, in show_tx
    row_to_html(txout, 'o', 'i', 'Not yet redeemed')
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1595, in row_to_html
    abe.show_tx_row_to_html_impl(chain, body, asset_txid_dict, binscript, script_type, data)
  File "/Users/michael/repos/multichain-explorer/Mce/abe.py", line 1261, in show_tx_row_to_html_impl
    assetref = asset_txid_dict[dict['assetref']]['assetref']
KeyError: 'b21f78291b609eceffa576717ebb1110'
127.0.0.1 - - [07/Nov/2017 20:52:45] "GET /MultiChain%20chain1/tx/63c57e6afd1deb251c3c41219bada002b2b1763fa70ee84892edd917b453611e HTTP/1.1" 500 59
RPC failed: [Errno socket error] [Errno 61] Connection refused
catch_up_rpc: abort
Opened /Users/michael/.multichain/monet/blocks/blk00000.dat
[Errno socket error] [Errno 61] Connection refused
127.0.0.1 - - [07/Nov/2017 20:52:53] "GET / HTTP/1.1" 200 2793
RPC failed: [Errno socket error] [Errno 61] Connection refused
catch_up_rpc: abort
Opened /Users/michael/.multichain/monet/blocks/blk00000.dat
127.0.0.1 - - [07/Nov/2017 20:52:53] "GET /MultiChain%20chain1/recent?random=0.4414431583956733 HTTP/1.1" 200 103
```

It looks like some i query some address i have no permissions. But i should not abort

**Comment by sparshprogrammer** [comment]
i am also getting the same error

**Comment by seyacat** [comment]
try using explicit port on multichain.conf file
~/.multichain/yourchain/multichain.conf
....
rpcport=2890
