### ISSUE TITLE
Can't use MySQL db

### ISSUE THREAD

**Issue by facundomedica** [MultiChain/multichain-explorer#32]
I'm trying to use Multichain's explorer with a mysql database but I'm getting:

```bash
root@instance-4:~/explorer# python -m Mce.abe --config mychain.conf --commit-bytes 100000 --no-serve
ddl_implicit_commit=true
create_table_epilogue=''
Mce/SqlAbstraction.py:437: Warning: Converting column 'a' from VARCHAR to TEXT
  sql.cursor().execute(stmt)
Mce/SqlAbstraction.py:437: Warning: Converting column 'b' from VARCHAR to TEXT
  sql.cursor().execute(stmt)
max_varchar=4294967295
clob_type=LONGTEXT
binary_type=binary
int_type=int
sequence_type=update
limit_style=native
Mce/SqlAbstraction.py:407: Warning: Truncated incorrect INTEGER value: 'foo'
  sql.cursor().execute(stmt, params)
Mce/SqlAbstraction.py:407: Warning: Truncated incorrect INTEGER value: 'bar'
  sql.cursor().execute(stmt, params)
Mce/SqlAbstraction.py:407: Warning: Truncated incorrect INTEGER value: 'baz'
  sql.cursor().execute(stmt, params)
Mce/SqlAbstraction.py:407: Warning: Truncated incorrect DOUBLE value: 'foo'
  sql.cursor().execute(stmt, params)
Mce/SqlAbstraction.py:407: Warning: Truncated incorrect DOUBLE value: 'bar'
  sql.cursor().execute(stmt, params)
Mce/SqlAbstraction.py:407: Warning: Truncated incorrect DOUBLE value: 'baz'
  sql.cursor().execute(stmt, params)
((0L, 0L),)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/explorer/Mce/abe.py", line 4300, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/explorer/Mce/abe.py", line 4294, in main
    store = make_store(args)
  File "/root/explorer/Mce/abe.py", line 193, in make_store
    store = DataStore.new(args)
  File "Mce/DataStore.py", line 4348, in new
    return DataStore(args)
  File "Mce/DataStore.py", line 187, in __init__
    store.initialize()
  File "Mce/DataStore.py", line 725, in initialize
    store.configure()
  File "Mce/DataStore.py", line 1072, in configure
    config = store._sql.configure()
  File "Mce/SqlAbstraction.py", line 547, in configure
    sql.configure_concat_style()
  File "Mce/SqlAbstraction.py", line 887, in configure_concat_style
    raise Exception("Can not find suitable concatenation style.")
Exception: Can not find suitable concatenation style.
```

I couldn't find anything about this on bitcoin-abe repo, so I though I should ask here first.

**Comment by reiven** [comment]
As far as i remember, this implementation only supports SQLite, but it will be great to add MySQL support

**Comment by facundomedica** [comment]
Yeah, I just searched about PostgreSQL and found an old issue about that. Closing...
