### ISSUE TITLE
SQL - not working

### ISSUE THREAD

**Issue by albabosh** [MultiChain/multichain-explorer#38]
PostgreSQL shows this error:

Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 100000, 'chain_id': 1, 'loader': u'default', 'conf': None, 'dirname': u'/home/ops/.multichain/mutoken', 'id': Decimal('3')}
Traceback (most recent call last):
  File "Mce/DataStore.py", line 2903, in catch_up
    store.catch_up_dir(dircfg)
  File "Mce/DataStore.py", line 3215, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Mce/DataStore.py", line 3347, in import_blkdat
    store.import_block(b, chain = chain)
  File "Mce/DataStore.py", line 1201, in import_block
    tx['tx_id'] = store.import_tx(tx, pos == 0, chain)
  File "Mce/DataStore.py", line 1986, in import_tx
    binscript = store.binout(txout['scriptPubKey'])
  File "Mce/SqlAbstraction.py", line 77, in from_hex
    return None if x is None else x.decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

**Comment by FranciscoThiesen** [comment]
I am facing this exact same problem with PostgreSQL. Have you found a solution for it? @albabosh
