### ISSUE TITLE
KeyError: '5a8ec07be00d3cf3824377aa0f1cfb7c'

### ISSUE THREAD

**Issue by oury1** [MultiChain/multichain-explorer#42]
Hi everyone 
I see all the latest transaction and all the stream fine but 
when i click on transaction or  search the a transaction i have an error
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/oury/multichain-explorer-master/Mce/abe.py", line 321, in __call__
    handler(page)
  File "/home/oury/multichain-explorer-master/Mce/abe.py", line 1197, in handle_tx
    return abe.show_tx(page, tx)
  File "/home/oury/multichain-explorer-master/Mce/abe.py", line 1671, in show_tx
    row_to_html(txout, 'o', 'i', 'Not yet redeemed')
  File "/home/oury/multichain-explorer-master/Mce/abe.py", line 1598, in row_to_html
    abe.show_tx_row_to_html_impl(chain, body, asset_txid_dict, binscript, script_type, data)
  File "/home/oury/multichain-explorer-master/Mce/abe.py", line 1370, in show_tx_row_to_html_impl
    assetref = asset_txid_dict[assettxid]['assetref']
KeyError: '5a8ec07be00d3cf3824377aa0f1cfb7c'
192.168.0.2 - - [15/Apr/2018 20:58:09] "GET //Fidealis/tx/96453e15c64ee3c9648be61dddb6751ce6e8c6125e54dc256ce0fbe67c107d58 HTTP/1.1" 500 59

for all the transaction

someone can help

thanks

**Comment by tloriato** [comment]
Was the transaction included in any blocks? How many confs?
