### ISSUE TITLE
Dangerous use of .index in Parse Functions (Error on parse_new_issuance_metadata_10007)

### ISSUE THREAD

**Issue by tloriato** [MultiChain/multichain-explorer#46]
```
Traceback (most recent call last):
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3115, in catch_up
explorernode_1  |     if not store.catch_up_rpc(dircfg):
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3711, in catch_up_rpc
explorernode_1  |     store.import_block(block, chain = chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 1404, in import_block
explorernode_1  |     tx['tx_id'] = store.import_and_commit_tx(tx, pos == 0, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 2437, in import_and_commit_tx
explorernode_1  |     tx_id = store.import_tx(tx, is_coinbase, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 2288, in import_tx
explorernode_1  |     opdrop_type, val = util.parse_op_drop_data(data, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 426, in parse_op_drop_data
explorernode_1  |     return func(data)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 439, in parse_op_drop_data_10007
explorernode_1  |     retval = parse_new_issuance_metadata_10007(data[5:])
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 753, in parse_new_issuance_metadata_10007
explorernode_1  |     fname = searchdata[:searchdata.index("\0")]
explorernode_1  | ValueError: substring not found
```
string.index throws an error when it doesn't encounter the specified substring, which is a dangerous behavior. I've been trying to fix this, but I don't completely understand the function yet.

At the time of error:

```
>print(searchdata)
> nd,receive}
```

**Comment by tloriato** [comment]
Just found out that the same error occurs when trying to parse smartfilters directly from the example.

**Comment by tloriato** [comment]
Managed to reproduce it!

Here's the decoded tx:

```
{"locktime": 0, "version": 1, "vin": [{"sequence": 4294967295, "scriptSig": {"hex": "47304402206bb96e60723d4e541e0bc5ca3dbe8af38f6dd41ba186d5bc49a30e2dc4bf604a0220705cf64e3f101f21cafd68e40d390a7c1d4774754a0b82082784dbd0c391668e012103a79dc4304975520983739cac6208353accd054de4ac66444fd99b235c1d2d987", "asm": "304402206bb96e60723d4e541e0bc5ca3dbe8af38f6dd41ba186d5bc49a30e2dc4bf604a0220705cf64e3f101f21cafd68e40d390a7c1d4774754a0b82082784dbd0c391668e01 03a79dc4304975520983739cac6208353accd054de4ac66444fd99b235c1d2d987"}, "vout": 2, "txid": "b17078048ad8fcc9d2aa20d4a1a2bd04762f7a7e4018041d87923afcd01c9bef"}], "vout": [{"permissions": [{"activate": True, "for": {"type": "asset", "name": "16.538.122/0001-76", "assetref": "38-265-28849"}, "receive": False, "timestamp": 1565320986, "startblock": 0, "send": False, "custom": [], "admin": False, "issue": False, "endblock": 4294967295}], "scriptPubKey": {"reqSigs": 1, "hex": "76a914a48bf1b3b4dbe11caeee0ead9de1f9cfa92aead988ac1473706b6504bda2a1d420aad2c9fcd88a047870b1751473706b700020000000000000ffffffff1ae74c5d75", "addresses": ["1PEst6wLCHW1o77hBrM9kf4w5o5LdVpQtFabH6"], "asm": "OP_DUP OP_HASH160 a48bf1b3b4dbe11caeee0ead9de1f9cfa92aead9 OP_EQUALVERIFY OP_CHECKSIG 73706b6504bda2a1d420aad2c9fcd88a047870b1 OP_DROP 73706b700020000000000000ffffffff1ae74c5d OP_DROP", "type": "pubkeyhash"}, "value": 0, "n": 0}, {"scriptPubKey": {"reqSigs": 1, "hex": "76a914cdd4924550172b10ad417ebfcc82e530d1b2415b88ac", "addresses": ["1UpVxG6egdSqCXWdFEeH1mSVQ2oJpAfNkXokUv"], "asm": "OP_DUP OP_HASH160 cdd4924550172b10ad417ebfcc82e530d1b2415b OP_EQUALVERIFY OP_CHECKSIG", "type": "pubkeyhash"}, "value": 0, "n": 1}], "txid": "d565fb7593aed2e72f7a973903e8d09091752e95f67a9ff085446afbdf30799a"}
```

Error log:
```
Traceback (most recent call last):
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3142, in catch_up
explorernode_1  |     if not store.catch_up_rpc(dircfg):
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3713, in catch_up_rpc
explorernode_1  |     store.import_block(block, chain = chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 1431, in import_block
explorernode_1  |     tx['tx_id'] = store.import_and_commit_tx(tx, pos == 0, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 2464, in import_and_commit_tx
explorernode_1  |     tx_id = store.import_tx(tx, is_coinbase, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 2315, in import_tx
explorernode_1  |     opdrop_type, val = util.parse_op_drop_data(data, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 426, in parse_op_drop_data
explorernode_1  |     return func(data)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 439, in parse_op_drop_data_10007
explorernode_1  |     retval = parse_new_issuance_metadata_10007(data[5:])
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 752, in parse_new_issuance_metadata_10007
explorernode_1  |     fname = searchdata[:searchdata.index("\0")]
explorernode_1  | ValueError: substring not found
```

**Comment by tloriato** [comment]
Turns out I was calling the RPC with wrong parameters (somehow Multichain was accepting and inserting in the chain?). Gonna investigate the real cause of problem.

**Comment by tloriato** [comment]
Managed to reproduced it with this new asset issuance:

```
{
    "hex" : "01000000014fa85f270246f564328d921f499f784f034b96db78b235ce7a1e2009c929b763000000006b483045022100b22e6b32828749544d35a38b9255b9d2b54576362a09c9bf84a20c90bd5f773502206ddce68b5e38c52a9212c4f3329ec2179be5a6f10470c59a1bdb7209845d46d5012103ce1f4a63e29dbcb1d210d3400e269719bc238caa1f35e95ec08287173a587254ffffffff0300000000000000002776a914babd6ea1b938c86de1a80656e41ce8bb4741c5b088ac0c73706b670000000000000000750000000000000000fd62034d5d0373706b6e0100012033343031372e3033373030303134342f4e462d313536353439333738363939310041040100000000020101000601020005fd21037b6904636e706a53691233342e3031372e3033372f303030312d34346907656d6973736f72536926315345724a6a6470753854696d7a593174536279354b38444d3848586b324635735267534d31690970726573746163616f7b690c616c69715365727669636f73536904302e3136690b6261736543616c63756c6f5369063430392e3431690a636f645365727669636f53690232326912636f645472696275744d756e69636970696f6c0010c8ef690d6461746150726573746163616f5369083139333331313034690e646573636f6e746f496e636f6e64536904332e3232690d6469736372696d696e6163616f5369517477656c7665206469616d6f6e6420696c6c6567616c20686f76657220737065616b20696e76657374207369737465722067726176697479206865616420726563616c6c2074726561742063657265616c6910657869676962696c69646164654953534333690f696e63656e7469766f46697363616c4332690969737352657469646f433169096974656d4c6973746153690534332e383669166f7074616e746553696d706c65734e6163696f6e616c4331690f6f7574726173526574656e636f6573536904312e3432691470726566656974757261496e636964656e6369616c0010ca73690f726567696d654573705472696275744335690c72657370526574656e63616f4332690776616c43736c6c536904302e3332690b76616c44656475636f6573536904392e3830690776616c496e7373536904342e3737690676616c49737353690536372e3539690c76616c4c697175694e6673655369063334352e3131690b76616c5365727669636f735369063432322e3433691076616c546f74616c5472696275746f7353690531332e31367d690a636f6e7374436976696c7b7d690d696e7465726d6564696172696f7b245323690369156964656e74696669636163616f496e7465726d6564691238312e3034332e3434352f303030312d353069116e6f6d6552617a616f496e7465726d6564691e4672616e636973636f2046696f726f742052617ac3a36f20536f6369616c690e636964616465496e7465726d65646907333130303338397d756a00000000000000001976a914babd6ea1b938c86de1a80656e41ce8bb4741c5b088ac00000000",
    "txid" : "aef8136d4cb3bf60f0daee5e19c69c79e5f9e00e8ea59e487bf66e8260820997",
    "version" : 1,
    "locktime" : 0,
    "vin" : [
        {
            "txid" : "63b729c909201e7ace35b278db964b034f789f491f928d3264f54602275fa84f",
            "vout" : 0,
            "scriptSig" : {
                "asm" : "3045022100b22e6b32828749544d35a38b9255b9d2b54576362a09c9bf84a20c90bd5f773502206ddce68b5e38c52a9212c4f3329ec2179be5a6f10470c59a1bdb7209845d46d501 03ce1f4a63e29dbcb1d210d3400e269719bc238caa1f35e95ec08287173a587254",
                "hex" : "483045022100b22e6b32828749544d35a38b9255b9d2b54576362a09c9bf84a20c90bd5f773502206ddce68b5e38c52a9212c4f3329ec2179be5a6f10470c59a1bdb7209845d46d5012103ce1f4a63e29dbcb1d210d3400e269719bc238caa1f35e95ec08287173a587254"
            },
            "sequence" : 4294967295
        }
    ],
    "vout" : [
        {
            "value" : 0,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 babd6ea1b938c86de1a80656e41ce8bb4741c5b0 OP_EQUALVERIFY OP_CHECKSIG 73706b670000000000000000 OP_DROP",
                "hex" : "76a914babd6ea1b938c86de1a80656e41ce8bb4741c5b088ac0c73706b67000000000000000075",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1SErJjdpu8TimzY1tSby5K8DM8HXk2F5sRgSM1"
                ]
            },
            "assets" : [
                {
                    "name" : "34017.037000144/NF-1565493786991",
                    "issuetxid" : "aef8136d4cb3bf60f0daee5e19c69c79e5f9e00e8ea59e487bf66e8260820997",
                    "assetref" : "32-1257-63662",
                    "qty" : 0,
                    "raw" : 0,
                    "type" : "issuefirst"
                }
            ]
        },
        {
            "value" : 0,
            "n" : 1,
            "scriptPubKey" : {
                "asm" : "73706b6e0100012033343031372e3033373030303134342f4e462d313536353439333738363939310041040100000000020101000601020005fd21037b6904636e706a53691233342e3031372e3033372f303030312d34346907656d6973736f72536926315345724a6a6470753854696d7a593174536279354b38444d3848586b324635735267534d31690970726573746163616f7b690c616c69715365727669636f73536904302e3136690b6261736543616c63756c6f5369063430392e3431690a636f645365727669636f53690232326912636f645472696275744d756e69636970696f6c0010c8ef690d6461746150726573746163616f5369083139333331313034690e646573636f6e746f496e636f6e64536904332e3232690d6469736372696d696e6163616f5369517477656c7665206469616d6f6e6420696c6c6567616c20686f76657220737065616b20696e76657374207369737465722067726176697479206865616420726563616c6c2074726561742063657265616c6910657869676962696c69646164654953534333690f696e63656e7469766f46697363616c4332690969737352657469646f433169096974656d4c6973746153690534332e383669166f7074616e746553696d706c65734e6163696f6e616c4331690f6f7574726173526574656e636f6573536904312e3432691470726566656974757261496e636964656e6369616c0010ca73690f726567696d654573705472696275744335690c72657370526574656e63616f4332690776616c43736c6c536904302e3332690b76616c44656475636f6573536904392e3830690776616c496e7373536904342e3737690676616c49737353690536372e3539690c76616c4c697175694e6673655369063334352e3131690b76616c5365727669636f735369063432322e3433691076616c546f74616c5472696275746f7353690531332e31367d690a636f6e7374436976696c7b7d690d696e7465726d6564696172696f7b245323690369156964656e74696669636163616f496e7465726d6564691238312e3034332e3434352f303030312d353069116e6f6d6552617a616f496e7465726d6564691e4672616e636973636f2046696f726f742052617ac3a36f20536f6369616c690e636964616465496e7465726d65646907333130303338397d OP_DROP OP_RETURN",
                "hex" : "4d5d0373706b6e0100012033343031372e3033373030303134342f4e462d313536353439333738363939310041040100000000020101000601020005fd21037b6904636e706a53691233342e3031372e3033372f303030312d34346907656d6973736f72536926315345724a6a6470753854696d7a593174536279354b38444d3848586b324635735267534d31690970726573746163616f7b690c616c69715365727669636f73536904302e3136690b6261736543616c63756c6f5369063430392e3431690a636f645365727669636f53690232326912636f645472696275744d756e69636970696f6c0010c8ef690d6461746150726573746163616f5369083139333331313034690e646573636f6e746f496e636f6e64536904332e3232690d6469736372696d696e6163616f5369517477656c7665206469616d6f6e6420696c6c6567616c20686f76657220737065616b20696e76657374207369737465722067726176697479206865616420726563616c6c2074726561742063657265616c6910657869676962696c69646164654953534333690f696e63656e7469766f46697363616c4332690969737352657469646f433169096974656d4c6973746153690534332e383669166f7074616e746553696d706c65734e6163696f6e616c4331690f6f7574726173526574656e636f6573536904312e3432691470726566656974757261496e636964656e6369616c0010ca73690f726567696d654573705472696275744335690c72657370526574656e63616f4332690776616c43736c6c536904302e3332690b76616c44656475636f6573536904392e3830690776616c496e7373536904342e3737690676616c49737353690536372e3539690c76616c4c697175694e6673655369063334352e3131690b76616c5365727669636f735369063432322e3433691076616c546f74616c5472696275746f7353690531332e31367d690a636f6e7374436976696c7b7d690d696e7465726d6564696172696f7b245323690369156964656e74696669636163616f496e7465726d6564691238312e3034332e3434352f303030312d353069116e6f6d6552617a616f496e7465726d6564691e4672616e636973636f2046696f726f742052617ac3a36f20536f6369616c690e636964616465496e7465726d65646907333130303338397d756a",
                "type" : "nulldata"
            }
        },
        {
            "value" : 0,
            "n" : 2,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 babd6ea1b938c86de1a80656e41ce8bb4741c5b0 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914babd6ea1b938c86de1a80656e41ce8bb4741c5b088ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1SErJjdpu8TimzY1tSby5K8DM8HXk2F5sRgSM1"
                ]
            }
        }
    ],
    "issue" : {
        "type" : "issuefirst",
        "name" : "34017.037000144/NF-1565493786991",
        "multiple" : 1,
        "open" : true,
        "details" : {
            "cnpj" : "34.017.037/0001-44",
            "emissor" : "1SErJjdpu8TimzY1tSby5K8DM8HXk2F5sRgSM1",
            "prestacao" : {
                "aliqServicos" : "0.16",
                "baseCalculo" : "409.41",
                "codServico" : "22",
                "codTributMunicipio" : 1100015,
                "dataPrestacao" : "19331104",
                "descontoIncond" : "3.22",
                "discriminacao" : "twelve diamond illegal hover speak invest sister gravity head recall treat cereal",
                "exigibilidadeISS" : "3",
                "incentivoFiscal" : "2",
                "issRetido" : "1",
                "itemLista" : "43.86",
                "optanteSimplesNacional" : "1",
                "outrasRetencoes" : "1.42",
                "prefeituraIncidencia" : 1100403,
                "regimeEspTribut" : "5",
                "respRetencao" : "2",
                "valCsll" : "0.32",
                "valDeducoes" : "9.80",
                "valInss" : "4.77",
                "valIss" : "67.59",
                "valLiquiNfse" : "345.11",
                "valServicos" : "422.43",
                "valTotalTributos" : "13.16"
            },
            "constCivil" : {
            },
            "intermediario" : {
                "identificacaoIntermed" : "81.043.445/0001-50",
                "nomeRazaoIntermed" : "Francisco Fiorot Raz\u00E3o Social",
                "cidadeIntermed" : "3100389"
            }
        }
    },
    "blockhash" : "0000fd285d52bb849d980c7169fccaf8ec4059c2cb2da521ed3ae92dcf25ac33",
    "confirmations" : 5,
    "time" : 1565493787,
    "blocktime" : 1565493787
}
```

I don't see anything particularly wrong with the details format but the empty object is the prime suspect here. I'll try to remove it from my generator and see how it goes.

**Comment by tloriato** [comment]
No luck, it happened as well with this transaction that seems completely fine:
```
{
    "hex" : "010000000188e3188e0e96e3b900fea177d0eaa68391c12b0e0c78407ee45c18dce654d152000000006a47304402206320bd3bc791bca1be8ca5b546d57ce5c80791d144eec74fa7969c7f2c06cff002202d3cb4a2f31fe36ed1969e9f61eb3cdaa83c68183448eb5aa7c02552f8215b62012102bc14ab878ed07a7ed84653d5f600f6cb134539367d82487d2d0790efff1475bbffffffff0300000000000000002776a914c0b0254c5aa7cc6b0336d3a8931417ac9500345d88ac0c73706b670000000000000000750000000000000000fd7f034d7a0373706b6e0100012034373431322e3538323030303138372f4e462d313536353439343731323633310041040100000000020101000601020005fd3e037b6904636e706a53691234372e3431322e3538322f303030312d38376907656d6973736f7253692631543355667a714b704c456d435932353463436b67596262344567755776396d4570465a3963690970726573746163616f7b690c616c69715365727669636f73536904302e3036690b6261736543616c63756c6f5369063334332e30306907636f64436e616553690e3130363634393030303030313937690a636f645365727669636f53690234386912636f645472696275744d756e69636970696f53690731313030333739690d6461746150726573746163616f5369083139323731313135690e646573636f6e746f496e636f6e64536904302e3333690d6469736372696d696e6163616f53694b67697665207374616d70206865617274206865696768742065746869637320646f6e61746520776f6d616e20676c6f772073747265657420766963746f7279206f70657261206372696d656910657869676962696c69646164654953534335690f696e63656e7469766f46697363616c4331690969737352657469646f433169096974656d4c6973746153690534332e353069166f7074616e746553696d706c65734e6163696f6e616c4332690f6f7574726173526574656e636f6573536904332e3335691470726566656974757261496e636964656e63696153690731313030333436690f726567696d654573705472696275744333690c72657370526574656e63616f4332690776616c43736c6c536904322e3234690b76616c44656475636f6573536904322e3934690776616c496e7373536904342e3037690676616c49737353690532302e3738690c76616c4c697175694e6673655369063331342e3234690676616c506973536904312e3236690b76616c5365727669636f735369063334362e3237691076616c546f74616c5472696275746f7353690531302e32357d690d696e7465726d6564696172696f7b245323690369156964656e74696669636163616f496e7465726d6564691235372e3334332e3738302f303030312d393069116e6f6d6552617a616f496e7465726d6564691c416cc3ad63696120506573736f742052617ac3a36f20536f6369616c690e636964616465496e7465726d65646907313238343830307d756a00000000000000001976a914c0b0254c5aa7cc6b0336d3a8931417ac9500345d88ac00000000",
    "txid" : "a329363bd157c57feba47e5217b882364d995b69d4995da05f924644a962dde6",
    "version" : 1,
    "locktime" : 0,
    "vin" : [
        {
            "txid" : "52d154e6dc185ce47e40780c0e2bc19183a6ead077a1fe00b9e3960e8e18e388",
            "vout" : 0,
            "scriptSig" : {
                "asm" : "304402206320bd3bc791bca1be8ca5b546d57ce5c80791d144eec74fa7969c7f2c06cff002202d3cb4a2f31fe36ed1969e9f61eb3cdaa83c68183448eb5aa7c02552f8215b6201 02bc14ab878ed07a7ed84653d5f600f6cb134539367d82487d2d0790efff1475bb",
                "hex" : "47304402206320bd3bc791bca1be8ca5b546d57ce5c80791d144eec74fa7969c7f2c06cff002202d3cb4a2f31fe36ed1969e9f61eb3cdaa83c68183448eb5aa7c02552f8215b62012102bc14ab878ed07a7ed84653d5f600f6cb134539367d82487d2d0790efff1475bb"
            },
            "sequence" : 4294967295
        }
    ],
    "vout" : [
        {
            "value" : 0,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 c0b0254c5aa7cc6b0336d3a8931417ac9500345d OP_EQUALVERIFY OP_CHECKSIG 73706b670000000000000000 OP_DROP",
                "hex" : "76a914c0b0254c5aa7cc6b0336d3a8931417ac9500345d88ac0c73706b67000000000000000075",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1T3UfzqKpLEmCY254cCkgYbb4EguWv9mEpFZ9c"
                ]
            },
            "assets" : [
                {
                    "name" : "47412.582000187/NF-1565494712631",
                    "issuetxid" : "a329363bd157c57feba47e5217b882364d995b69d4995da05f924644a962dde6",
                    "assetref" : "28-1244-10659",
                    "qty" : 0,
                    "raw" : 0,
                    "type" : "issuefirst"
                }
            ]
        },
        {
            "value" : 0,
            "n" : 1,
            "scriptPubKey" : {
                "asm" : "73706b6e0100012034373431322e3538323030303138372f4e462d313536353439343731323633310041040100000000020101000601020005fd3e037b6904636e706a53691234372e3431322e3538322f303030312d38376907656d6973736f7253692631543355667a714b704c456d435932353463436b67596262344567755776396d4570465a3963690970726573746163616f7b690c616c69715365727669636f73536904302e3036690b6261736543616c63756c6f5369063334332e30306907636f64436e616553690e3130363634393030303030313937690a636f645365727669636f53690234386912636f645472696275744d756e69636970696f53690731313030333739690d6461746150726573746163616f5369083139323731313135690e646573636f6e746f496e636f6e64536904302e3333690d6469736372696d696e6163616f53694b67697665207374616d70206865617274206865696768742065746869637320646f6e61746520776f6d616e20676c6f772073747265657420766963746f7279206f70657261206372696d656910657869676962696c69646164654953534335690f696e63656e7469766f46697363616c4331690969737352657469646f433169096974656d4c6973746153690534332e353069166f7074616e746553696d706c65734e6163696f6e616c4332690f6f7574726173526574656e636f6573536904332e3335691470726566656974757261496e636964656e63696153690731313030333436690f726567696d654573705472696275744333690c72657370526574656e63616f4332690776616c43736c6c536904322e3234690b76616c44656475636f6573536904322e3934690776616c496e7373536904342e3037690676616c49737353690532302e3738690c76616c4c697175694e6673655369063331342e3234690676616c506973536904312e3236690b76616c5365727669636f735369063334362e3237691076616c546f74616c5472696275746f7353690531302e32357d690d696e7465726d6564696172696f7b245323690369156964656e74696669636163616f496e7465726d6564691235372e3334332e3738302f303030312d393069116e6f6d6552617a616f496e7465726d6564691c416cc3ad63696120506573736f742052617ac3a36f20536f6369616c690e636964616465496e7465726d65646907313238343830307d OP_DROP OP_RETURN",
                "hex" : "4d7a0373706b6e0100012034373431322e3538323030303138372f4e462d313536353439343731323633310041040100000000020101000601020005fd3e037b6904636e706a53691234372e3431322e3538322f303030312d38376907656d6973736f7253692631543355667a714b704c456d435932353463436b67596262344567755776396d4570465a3963690970726573746163616f7b690c616c69715365727669636f73536904302e3036690b6261736543616c63756c6f5369063334332e30306907636f64436e616553690e3130363634393030303030313937690a636f645365727669636f53690234386912636f645472696275744d756e69636970696f53690731313030333739690d6461746150726573746163616f5369083139323731313135690e646573636f6e746f496e636f6e64536904302e3333690d6469736372696d696e6163616f53694b67697665207374616d70206865617274206865696768742065746869637320646f6e61746520776f6d616e20676c6f772073747265657420766963746f7279206f70657261206372696d656910657869676962696c69646164654953534335690f696e63656e7469766f46697363616c4331690969737352657469646f433169096974656d4c6973746153690534332e353069166f7074616e746553696d706c65734e6163696f6e616c4332690f6f7574726173526574656e636f6573536904332e3335691470726566656974757261496e636964656e63696153690731313030333436690f726567696d654573705472696275744333690c72657370526574656e63616f4332690776616c43736c6c536904322e3234690b76616c44656475636f6573536904322e3934690776616c496e7373536904342e3037690676616c49737353690532302e3738690c76616c4c697175694e6673655369063331342e3234690676616c506973536904312e3236690b76616c5365727669636f735369063334362e3237691076616c546f74616c5472696275746f7353690531302e32357d690d696e7465726d6564696172696f7b245323690369156964656e74696669636163616f496e7465726d6564691235372e3334332e3738302f303030312d393069116e6f6d6552617a616f496e7465726d6564691c416cc3ad63696120506573736f742052617ac3a36f20536f6369616c690e636964616465496e7465726d65646907313238343830307d756a",
                "type" : "nulldata"
            }
        },
        {
            "value" : 0,
            "n" : 2,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 c0b0254c5aa7cc6b0336d3a8931417ac9500345d OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914c0b0254c5aa7cc6b0336d3a8931417ac9500345d88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1T3UfzqKpLEmCY254cCkgYbb4EguWv9mEpFZ9c"
                ]
            }
        }
    ],
    "issue" : {
        "type" : "issuefirst",
        "name" : "47412.582000187/NF-1565494712631",
        "multiple" : 1,
        "open" : true,
        "details" : {
            "cnpj" : "47.412.582/0001-87",
            "emissor" : "1T3UfzqKpLEmCY254cCkgYbb4EguWv9mEpFZ9c",
            "prestacao" : {
                "aliqServicos" : "0.06",
                "baseCalculo" : "343.00",
                "codCnae" : "10664900000197",
                "codServico" : "48",
                "codTributMunicipio" : "1100379",
                "dataPrestacao" : "19271115",
                "descontoIncond" : "0.33",
                "discriminacao" : "give stamp heart height ethics donate woman glow street victory opera crime",
                "exigibilidadeISS" : "5",
                "incentivoFiscal" : "1",
                "issRetido" : "1",
                "itemLista" : "43.50",
                "optanteSimplesNacional" : "2",
                "outrasRetencoes" : "3.35",
                "prefeituraIncidencia" : "1100346",
                "regimeEspTribut" : "3",
                "respRetencao" : "2",
                "valCsll" : "2.24",
                "valDeducoes" : "2.94",
                "valInss" : "4.07",
                "valIss" : "20.78",
                "valLiquiNfse" : "314.24",
                "valPis" : "1.26",
                "valServicos" : "346.27",
                "valTotalTributos" : "10.25"
            },
            "intermediario" : {
                "identificacaoIntermed" : "57.343.780/0001-90",
                "nomeRazaoIntermed" : "Al\u00EDcia Pessot Raz\u00E3o Social",
                "cidadeIntermed" : "1284800"
            }
        }
    },
    "blockhash" : "00007fdd9c865a9c3a231a5d24336665b579286a7caa97d8167f6d4cc7999b25",
    "confirmations" : 42,
    "time" : 1565494712,
    "blocktime" : 1565494712
}
```

**Comment by tloriato** [comment]
This is my terminal output for variable `data` at line ~754. 

```
 47412.582000187/NF-1565494712631A�>{icnpjSi47.412.582/0001-87iemissorSi&1T3UfzqKpLEmCY254cCkgYbb4EguWv9mEpFZ9ci	prestacao{i
                   aliqServicosSi0.06i
                                      baseCalculoSi343.00icodCnaeSi10664900000197i
discriminacaoSiKgive stamp heart height ethics donate woman glow street victory opera crimeiexigibilidadeISSC5iincentivoFiscalC1i	issRetidoC1i	itemListaSi43.50ioptanteSimplesNacionalC2ioutrasRetencoesSi3.35iprefeituraIncidenciaSi1100346iregimeEspTributC3i
        respRetencaoC2ivalCsllSi2.24i
                                     valDeducoesSi2.94ivalInssSi4.07ivalIssSi20.78i
                                                                                   valLiquiNfseSi314.24ivalPisSi1.26i
                                                                                                                     valServicosintermediario{$S#iiidentificacaoIntermedi57.343.780/0001-90inomeRazaoIntermediAlícia Pessot Razão SocialicidadeIntermedi1284800}
```

And the **variable pos was 306**

**Comment by tloriato** [comment]
Managed to reproduce it and create the smallest possible example. It fails when the "details" object field in "issue(From)" is:

```
{
      "key1": "medium size string value just to fill space",
      "key2": "medium size string value just to fill space",
      "key3": "medium size string value just to fill space",
      "key4": "medium size string value just to fill space",
      "key5": "medium size string value just to fill space"
}
```

**ps: the assetname has 32 characters**

Remove "key5" and it works, insert it and it doesn't. I believe it's something related to total size? Very strange for python.

Node.js script if you would like to test (https://gist.github.com/tloriato/5f0fbb42426aae28850d94dd72d8c612)

**Comment by tloriato** [comment]
Another error in the same function:

```
explorernode_1  | Traceback (most recent call last):
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3157, in catch_up
explorernode_1  |     store.catch_up_dir(dircfg)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3819, in catch_up_dir
explorernode_1  |     store.import_blkdat(dircfg, ds, blkfile['name'])
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 3957, in import_blkdat
explorernode_1  |     store.import_block(b, chain = chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 1442, in import_block
explorernode_1  |     tx['tx_id'] = store.import_and_commit_tx(tx, pos == 0, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 2475, in import_and_commit_tx
explorernode_1  |     tx_id = store.import_tx(tx, is_coinbase, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/DataStore.py", line 2326, in import_tx
explorernode_1  |     opdrop_type, val = util.parse_op_drop_data(data, chain)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 426, in parse_op_drop_data
explorernode_1  |     return func(data)
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 439, in parse_op_drop_data_10007
explorernode_1  |     retval = parse_new_issuance_metadata_10007(data[5:])
explorernode_1  |   File "/root/.local/lib/python2.7/site-packages/Mce/util.py", line 728, in parse_new_issuance_metadata_10007
explorernode_1  |     if k in json_data:
explorernode_1  | TypeError: argument of type 'long' is not iterable
```

I believe he's trying to converted a string like "65496845000165" to long? That's the only "long" amount in my payload.
