### ISSUE TITLE
Error while syncing blocks

### ISSUE THREAD

**Issue by jonassunandar** [MultiChain/multichain-explorer#47]
Hey guys,
Love what you are doing!

But I get this error while trying to sync blocks from the existing blockchain.

```
block_tx 62 63
block_tx 63 64
Exception at 3388430958997887345
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 100000, 'chain_id': 1, 'loader': u'default', 'conf': None, 'dirname': u'/root/.multichain/pharmacy', 'id': 1}
Traceback (most recent call last):
  File "Mce/DataStore.py", line 2903, in catch_up
    store.catch_up_dir(dircfg)
  File "Mce/DataStore.py", line 3215, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Mce/DataStore.py", line 3337, in import_blkdat
    b = chain.ds_parse_block(ds)
  File "Mce/Chain/__init__.py", line 133, in ds_parse_block
    d['transactions'].append(chain.ds_parse_transaction(ds))
  File "Mce/Chain/__init__.py", line 126, in ds_parse_transaction
    return deserialize.parse_Transaction(ds)
  File "Mce/deserialize.py", line 90, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Mce/deserialize.py", line 46, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Mce/BCDataStream.py", line 71, in read_uint32
    def read_uint32 (self): return self._read_num('<I')
  File "Mce/BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 4 bytes

```

MultiChain 1.0.9 Daemon (protocol 10004-10012)
Latest multichain-explorer version.
Ubuntu 18.04.3 LTS

Any idea why?
Thanks in advance!

**Comment by gidgreen** [comment]
We'd need to see your blockchain in order to be able to debug this. If that's an option, please stop your node, zip up your blockchain directory, then send it to multichain dot debug at gmail dot com.

**Comment by jonassunandar** [comment]
I already sent you my blockchain dir via email. Please take a look.
